version: "3.9"
services:
  django:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
    ports:
      - "8000:8000"
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '15672:15672'
    depends_on:
      - django
  celery:
    build: .
    working_dir: /code
    volumes:
      - .:/code
    command:  celery -A conf.celery worker -l INFO
    depends_on:
      - django
      - rabbitmq
  flower:
    container_name: scrap_task_flower
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - .:/code
    depends_on:
      - django
      - rabbitmq
      - celery
    command: celery -A conf.celery flower
  selenium-hub:
    restart: always
    image: selenium/hub:3.14.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
  chrome:
    restart: always
    image: selenium/node-chrome-debug:3.14.0
    ports:
      - "5900-5999:5900"
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      DBUS_SESSION_BUS_ADDRESS: "/dev/null"
    links:
      - selenium-hub:hub