# Generated by Django 3.2 on 2021-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('score', models.FloatField(verbose_name='Рейтинг')),
                ('qty_subscribers', models.PositiveIntegerField(verbose_name='Количество подписчиков')),
                ('subscriptions', models.PositiveIntegerField(verbose_name='Количество подписок')),
                ('qty_posts', models.PositiveIntegerField(verbose_name='Количество постов')),
                ('avg_amount_likes_on_all_posts', models.FloatField(verbose_name='Среднее количество лайков на всех постах')),
                ('avg_amount_likes_on_last_20_posts', models.FloatField(verbose_name='Среднее количество лайков на последних 20 постах')),
            ],
        ),
    ]
