# Generated by Django 3.2 on 2021-08-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_person_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
    ]
