# Generated by Django 3.2 on 2021-08-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210826_0619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=1, max_length=128, verbose_name='User or Id'),
            preserve_default=False,
        ),
    ]
