# Generated by Django 3.2 on 2021-08-24 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210824_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='stats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.personstats'),
        ),
    ]
