# Generated by Django 3.2 on 2021-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_person_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='social_network',
            field=models.CharField(choices=[('default', 'Значение по умолчанию'), ('fb', 'Facebook'), ('inst', 'Instagram'), ('vk', 'vk')], default='default', max_length=128, verbose_name='Соцсеть'),
        ),
    ]
