# Generated by Django 3.2 on 2021-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_person_social_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='social_network',
            field=models.CharField(choices=[('none', 'Значение по умолчанию'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('VK', 'vk')], default='none', max_length=128, verbose_name='Соцсеть'),
        ),
    ]
