# Generated by Django 3.2 on 2021-08-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210810_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
