# Generated by Django 3.2 on 2021-08-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='score',
            field=models.FloatField(default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
