# Generated by Django 3.2 on 2021-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_person_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avg_amount_likes_on_all_posts',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее количество лайков на всех постах'),
        ),
        migrations.AlterField(
            model_name='person',
            name='avg_amount_likes_on_last_20_posts',
            field=models.FloatField(blank=True, null=True, verbose_name='Среднее количество лайков на последних 20 постах'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qty_posts',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество постов'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qty_subscribers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество подписчиков'),
        ),
        migrations.AlterField(
            model_name='person',
            name='social_network',
            field=models.CharField(blank=True, choices=[('none', 'Значение по умолчанию'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('VK', 'vk')], default='none', max_length=128, null=True, verbose_name='Соцсеть'),
        ),
        migrations.AlterField(
            model_name='person',
            name='subscriptions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество подписок'),
        ),
    ]
